# This playbook is to "Install the Gnome desktop" so to speak, (useful) Gnome
# applications go here
- name: Install Gnome applications
  hosts: localhost
  tasks:
    - name: Install from flatpak
      community.general.flatpak:
        state: present
        method: user
        name:
          - org.gnome.baobab
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.Characters
          - org.gnome.clocks
          - org.gnome.Contacts
          - org.gnome.Decibels
          - org.gnome.Epiphany
          - org.gnome.font-viewer
          - org.gnome.Logs
          - org.gnome.Loupe
          - org.gnome.Maps
          - org.gnome.Papers
          - org.gnome.Showtime
          - org.gnome.Snapshot
          - org.gnome.TextEditor
          - org.gnome.Weather
