- name: Download scripting runtimes installers
  hosts: localhost
  tasks:
    - name: nvm
      block:
        - import_tasks: ../common/install-from-github.yaml
          vars:
            repository: nvm-sh/nvm
            ref: v0.40.5
            installer: install.sh
            checksum_algorithm: sha256
            # sha256sum calculated Jun 22th, 2023
            checksum: 582070e4c44452c1d8d68e16fc786c2216ecba6bc6bf18dc280a03fdba6ed1a9
    - name: rbenv
      block:
        - import_tasks: ../common/install-from-github.yaml
          vars:
            repository: rbenv/rbenv-installer
            ref: a5350919f70fd398f327b2efcd072500ab7f29ce
            installer: bin/rbenv-installer
            checksum_algorithm: sha256
            # sha256sum calculated Jun 22th, 2023
            checksum: 9a1f19c4564cc8954bca75640d320fcc98cf40187d73531156629edd36606f2f
