# I still have some data on Firefox so I keep it installed but I prefer the
# flathub version, which is the officially provided by Mozilla.
- name: Firefox cleanup
  hosts: localhost
  tasks:
    - name: Remove apt based installation
      become: true
      apt:
        name: firefox
        state: absent
        purge: true
        autoremove: true
    - name: Remove snap based installation
      become: true
      community.general.snap:
        name: firefox
        state: absent
    - name: Install flatpak version
      community.general.flatpak:
        state: present
        method: user
        name: org.mozilla.firefox
