- name: Setup flatpak applications
  hosts: localhost
  tasks:
    - name: Ensure the calendar app starts on Monday
      command: /usr/bin/flatpak override --user --env=LC_TIME=en_DK.UTF-8 org.gnome.Calendar
