- name: Firefox cleanup
  hosts: localhost
  tasks:
    - name: Remove apt based installation
      become: true
      apt:
        name: firefox
        state: absent
        purge: true
        autoremove: true
    - name: Remove snap based installation
      become: true
      community.general.snap:
        name: firefox
        state: absent
