# While not ideal to have a "misc" playbook, this one should be short and sweet.
# Any deb application that doesn't need custom setup goes here. If anything
# needs custom setup or has a more relevant grouping goes to its own file.
# Things can be moved in or out of here as needed.
- name: Install assorted debs
  hosts: localhost
  tasks:
    - name: Install apt software
      become: true
      apt:
        name:
          - podman
        update_cache: yes
        state: present
    - name: Install orphan debs
      block:
        # NAPS2 it's also offered as a Flatpak but given the USB limitations with Flatpak
        # that version is literally useless for me.
        - name: naps2
          block:
            - import_tasks: ../../common/install-orphan-deb.yaml
              vars:
                naps2_version: 8.2.1
                deb_url: https://github.com/cyanfish/naps2/releases/download/v{{ naps2_version }}/naps2-{{ naps2_version }}-linux-x64.deb
                # Install NAPS2, sha256sum calculated Sep 01st, 2025
                deb_hash: sha256:8e23c4a6d7f0b75512459cc29a639ec395355f222375291ed674525c7c9cd4b7
        - name: Steam
          block:
            - import_tasks: ../../common/install-orphan-deb.yaml
              vars:
                steam_version: 1.0.0.85
                deb_url: https://repo.steampowered.com/steam/archive/stable/steam-launcher_{{ steam_version }}_amd64.deb
                # Install Steam, sha256sum calculated Jun 22st, 2026
                deb_hash: sha256:b44634a6a604ca7c8b23809d0f2a921a0348bb2081c8cb8944116d0799872b70
